Controllers/WarehousesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Proyecto_Pymes.Models.DB;

namespace Proyecto_Pymes.Controllers
{
    [Authorize]
    public class WarehousesController : Controller
    {
        private readonly DbPymesContext _context;

        public WarehousesController(DbPymesContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "Productor")]
        public async Task<IActionResult> Index()
        {
            try{
                int UserId = int.Parse(HttpContext.Session.GetString("UserID"));
                return _context.Warehouses != null ?
                View(await _context.Warehouses.Where(s => s.Status == 1 && s.UserId == UserId).ToListAsync()) :
                Problem("Entity set 'DbPymesContext.Categories'  is null.");
            }catch{
                return RedirectToAction("Privacy", "Home");
            }   
        }

        [Authorize(Roles = "Productor")]
        public async Task<IActionResult> Details(short? id)
        {
            if (id == null || _context.Warehouses == null)
            {
                return NotFound();
            }

            var warehouse = await _context.Warehouses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (warehouse == null)
            {
                return NotFound();
            }

            return View(warehouse);
        }

        [Authorize(Roles = "Productor")]
        public IActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Productor")]
        public async Task<IActionResult> Create([Bind("Id,Name,Location,CapacityMax,Status,RegisterDate,LastUpdate,UserId")] Warehouse warehouse)
        {
            if (ModelState.IsValid)
            {
                warehouse.UserId = int.Parse(HttpContext.Session.GetString("UserID"));
                _context.Add(warehouse);
                await _context.SaveChangesAsync();
                TempData["ShowModal"] = true;
            }
            return View(warehouse);
        }

        [Authorize(Roles = "Productor")]
        public async Task<IActionResult> Edit(short? id)
        {
            if (id == null || _context.Warehouses == null)
            {
                return NotFound();
            }

            var warehouse = await _context.Warehouses.FindAsync(id);
            if (warehouse == null)
            {
                return NotFound();
            }
            return View(warehouse);
        }

       
        [HttpPost]
        [Authorize(Roles = "Productor")]
        public async Task<IActionResult> Edit(Warehouse warehouse)
        {
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                            warehouse.LastUpdate = DateTime.Now;
                            _context.Warehouses.Update(warehouse);
                            await _context.SaveChangesAsync();
                            // Si todo ha ido bien, realiza el commit de la transacción
                            transaction.Commit();
                            TempData["ShowModal"] = true;

                        return View(); // Redirecciona a la página de lista después de la edición
                    }
                   
                    
                }
                catch (Exception ex)
                {
                    // Si ocurre un error, puedes manejarlo aquí y realizar un rollback de la transacción si es necesario
                    transaction.Rollback();
                    ModelState.AddModelError(string.Empty, "Ocurrió un error al guardar los datos.");
                    return View(warehouse);
                }
                return View(warehouse);
            }
        }



        [Authorize(Roles = "Productor")]
        public async Task<IActionResult> Delete(short? id)
        {
            var wareh = await _context.Warehouses.FirstOrDefaultAsync(m => m.Id == id);
            if (wareh == null)
            {
                return NotFound();
            }
            TempData["TownShipToDelete"] = (int)wareh.Id;
            TempData["Name"] = wareh.Name;
            TempData["ShowModalDelete"] = true;

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = "Productor")]
        public IActionResult UpdateShowModalDelete(bool value)
        {
            TempData["ShowModalDelete"] = value;
            return Json(new { success = true });
        }


        [Authorize(Roles = "Productor")]
        public async Task<IActionResult> ConfirmDelete(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var wareh = await _context.Warehouses.FindAsync(id);
            if (wareh == null)
            {
                return NotFound();
            }
            wareh.Status = 0; // O es valor Inactivo          
            _context.Warehouses.Update(wareh);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }



        private bool WarehouseExists(short id)
        {
          return (_context.Warehouses?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Warehouses/Create.cshtml
@model Proyecto_Pymes.Models.DB.Warehouse

@{
    ViewData["Title"] = "Create";
}

<h1 style="text-align:center; color: white;">Registrar Nuevo Almacen</h1>


<hr />
<div class="row">
    <div class="col-md-4 mx-auto my-5">
        <form asp-action="Create" style="color: white;" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Nombre:</label>
                <input type="text" asp-for="Name" class="form-control" placeholder="Nombre" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label">Ubicación (Opcional):</label>
                <input type="text" asp-for="Location" class="form-control" placeholder="Ubicación" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CapacityMax" class="control-label">Capacidad Máxima:</label>
                <input type="number" asp-for="CapacityMax" class="form-control" placeholder="Capacidad Máxima" />
                <span asp-validation-for="CapacityMax" class="text-danger"></span>
            </div>
            <div class="col-md-10">
                <div class="row">
                    <div class="col-md-6">
                        <div class="text-center">
                            <button type="submit" class="btn  btn-md  btn-block " style="background-color:#15718d; color:white;">Aceptar</button> <!-- Agregamos "btn-block" para que ocupe todo el ancho -->
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="text-center">
                            <a asp-action="Index" class="btn  btn-md btn-block " style="background-color:#bb2727; color:white;">Cancelar</a> <!-- Agregamos "btn-block" para que ocupe todo el ancho -->
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>



<div class="modal fade " id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Mensaje</h5>
            </div>
            <div class="modal-body">
                <p>Registro exitoso! <i class="fas fa-check-circle"></i></p>
            </div>
            <div class="modal-footer">
                <a asp-controller="Warehouses" asp-action="Index" class="btn btn-warning">Aceptar</a>
            </div>
        </div>
    </div>
</div>





@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    @if (TempData["ShowModal"] as bool? == true)
    {
        <script>
            $(document).ready(function () {
                $('#exampleModalCenter').modal('show');
            });
        </script>
    }
}

Views/Warehouses/Delete.cshtml
@model Proyecto_Pymes.Models.DB.Warehouse

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Warehouse</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CapacityMax)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CapacityMax)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastUpdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastUpdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Warehouses/Details.cshtml
@model Proyecto_Pymes.Models.DB.Warehouse

@{
    ViewData["Title"] = "Details";
}

<h1 style="text-align:center;">Detalles</h1>

<div>
   
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CapacityMax)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CapacityMax)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastUpdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastUpdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>
</div>

<div class="col-md-10">
    <div class="row">
        <div class="col-md-6">
            <div class="text-center">
              
                <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn  btn-md btn-block " style="background-color:#1c96ba; color:white;">Editar</a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="text-center">
                <a asp-action="Index" class="btn  btn-md btn-block " style="background-color:#253B8C; color:white;">Cancelar</a> <!-- Agregamos "btn-block" para que ocupe todo el ancho -->
            </div>
        </div>
    </div>
</div>

Views/Warehouses/Edit.cshtml
@model Proyecto_Pymes.Models.DB.Warehouse

@{
    ViewData["Title"] = "Edit";
}

<h1 style="text-align:center; color: white">Editar Almacen</h1>


<hr />
<div class="row">
    <div class="col-md-4 mx-auto my-5">
        <form asp-action="Edit" style="color: white">

            <input hidden asp-for="Id" />
            <input hidden asp-for="Status" />
            <input hidden asp-for="RegisterDate" />
            <input hidden asp-for="UserId" />

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"> Nombre:</label>
                <input type="text" asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label">Ubicacion (Opcional):</label>
                <input type="text" asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CapacityMax" class="control-label">Capacidad Maxima:</label>
                <input type="number" asp-for="CapacityMax" class="form-control" />
                <span asp-validation-for="CapacityMax" class="text-danger"></span>
            </div>
            <div class="col-md-10">
                <div class="row">
                    <div class="col-md-6">
                        <div class="text-center">
                            <button type="submit" class="btn  btn-md  btn-block " style="background-color:#15718d; color:white;">Actualizar</button> <!-- Agregamos "btn-block" para que ocupe todo el ancho -->
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="text-center">
                            <a asp-action="Index" class="btn  btn-md btn-block " style="background-color:#bb2727; color:white;">Cancelar</a> <!-- Agregamos "btn-block" para que ocupe todo el ancho -->
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Mensaje</h5>
            </div>
            <div class="modal-body">
                <p>Almacen Actualizado correctamente! <i class="fas fa-check-circle"></i></p>
            </div>
            <div class="modal-footer">
                <a asp-controller="Warehouses" asp-action="Index" class="btn btn-warning">Aceptar</a>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    @if (TempData["ShowModal"] as bool? == true)
    {
        <script>
            $(document).ready(function () {
                $('#exampleModalCenter').modal('show');
            });
        </script>
    }
}

Views/Warehouses/Index.cshtml
@model IEnumerable<Proyecto_Pymes.Models.DB.Warehouse>

@{
    ViewData["Title"] = "Index";
}

<h1 style="color: white;"  >Almacenes</h1>

<a asp-action="Create" class="btn" style="background-color: rgb(23, 114, 64); 
color:white; margin: 20px 20px 20px 0px; font-size: 20px "> Crear🔨</a>

<table class="table" style="color: white;" >
    <thead>
        <tr>
            <th>
                NOMBRE
            </th>
            <th>
                UBICACION
            </th>
            <th>
                CAPACIDAD MAXIMA
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CapacityMax)
            </td>
                <td>

                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn" style="background-color: #1c6eba; color: white; font-size: 17px">
                     ✏
                    </a>
                    @* <a asp-action="Details" asp-route-id="@item.Id" class="btn " style="background-color: #1c96ba; color: white;">
                        <i class="fas fa-details"></i> Detalles
                    </a> *@

                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn" style="background-color:#ba1c1c; color:white; margin-left: 10px; font-size: 17px ">
                              🗑</a>
                </td>
        </tr>
}
    </tbody>
</table>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmar Eliminación</h5>
            </div>
            <div class="modal-body">
                ¿Está seguro de que desea eliminar el siguiente registro? <br />
                Nombre: @TempData["Name"]
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <a asp-action="ConfirmDelete" asp-route-id="@TempData["TownShipToDelete"]" class="btn btn-danger">Eliminar</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @if (TempData["ShowModalDelete"] as bool? == true)
    {
        <script>
            $(document).ready(function () {
                $('#exampleModal').modal('show');


                $('#exampleModal').on('hidden.bs.modal', function () {

                    $.ajax({
                        url: '/TownShips/UpdateShowModalDelete',
                        method: 'POST',
                        data: { value: false }, // Enviar el valor false al servidor
                        success: function (data) {
                            // Opcional: Puedes realizar acciones adicionales después de cambiar el valor
                        }
                    });
                });
            });
        </script>
    }
}