Models/DB/Enterprise.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace Proyecto_Pymes.Models.DB;

public partial class Enterprise
{
    public short Id { get; set; }

    [Display(Name = "Nombre de la Agrupación")]
    [Required(ErrorMessage = "El campo es obligatorio.")]
    [StringLength(100, ErrorMessage = "El campo {0} debe tener entre {2} y {1} caracteres.", MinimumLength = 3)]
    [RegularExpression("^[A-Za-záéíóúüÁÉÍÓÚÜñÑ0-9\\s*]+$", ErrorMessage = "Solo se permiten letras, números.")]
    public string GroupName { get; set; } = null!;


    [Display(Name = "Dirección")]
    [Required(ErrorMessage = "El campo es obligatorio.")]
    [StringLength(149, ErrorMessage = "El campo {0} debe tener entre {2} y {1} caracteres.", MinimumLength = 2)]
    [RegularExpression("^[A-Za-záéíóúüÁÉÍÓÚÜñÑ0-9#,.\\s]+$", ErrorMessage = "Solo se permiten letras, números y los caracteres #,-,.,(,)")]
    public string Address { get; set; } = null!;


    //Acepta Nulos
    public byte[]? Image { get; set; }


    [Display(Name = "Descripción")]
    [Required(ErrorMessage = "El campo es obligatorio.")]
    [StringLength(149, ErrorMessage = "El campo {0} debe tener entre {2} y {1} caracteres.", MinimumLength = 3)]
    [RegularExpression("^[A-Za-záéíóúüÁÉÍÓÚÜñÑ0-9\\s*]+$", ErrorMessage = "Solo se permiten letras, números.")]
    public string Description { get; set; } = null!;

    public byte Status { get; set; }

    public DateTime RegisterDate { get; set; }

    public DateTime? LastUpdate { get; set; }

    public int UserId { get; set; }

    [Required(ErrorMessage = "Por favor, selecciona un Municipio.")]
    public short IdTownShip { get; set; }

    public virtual ICollection<BusinessManager> BusinessManagers { get; set; } = new List<BusinessManager>();

    public virtual TownShip? IdTownShipNavigation { get; set; } = null!;

    public virtual ICollection<ProducerCompany> ProducerCompanies { get; set; } = new List<ProducerCompany>();
}

Models/Enterprise.cs
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Enterprise
{
    public short Id { get; set; }

    public string GroupName { get; set; } = null!;

    public string Address { get; set; } = null!;

    public string PhoneNumber { get; set; } = null!;

    public byte[] Image { get; set; } = null!;

    public string Description { get; set; } = null!;

    public byte Status { get; set; }

    public DateTime RegisterDate { get; set; }

    public DateTime? LastUpdate { get; set; }

    public int UserId { get; set; }

    public short IdTownShip { get; set; }

    public virtual ICollection<BusinessManager> BusinessManagers { get; set; } = new List<BusinessManager>();

    public virtual TownShip IdTownShipNavigation { get; set; } = null!;

    public virtual ICollection<ProducerCompany> ProducerCompanies { get; set; } = new List<ProducerCompany>();
}

Controllers/EnterpriseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proyecto_Pymes.Models.DB;
using static Azure.Core.HttpHeader;
using static System.Net.Mime.MediaTypeNames;

namespace Proyecto_Pymes.Controllers
{
    [Authorize]
    public class EnterpriseController : Controller
    {

        private readonly DbPymesContext _context;

        public EnterpriseController(DbPymesContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "SuperUsuario")]
        public async Task<IActionResult> Index()
        {
            var enterprises = await _context.Enterprises
                .Where(e => e.Status == 1)
                .Include(e => e.IdTownShipNavigation)
                .ToListAsync();

            return View(enterprises);
        }


        [Authorize(Roles = "SuperUsuario")]
        public async Task<IActionResult> Create()
        {
            var towns = await _context.TownShips
                .Where(t => t.Status == 1)
                .ToListAsync();

            ViewBag.TownShips = new SelectList(towns, "Id", "Name");
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "SuperUsuario")]
        public async Task<IActionResult> Create(Enterprise enterprise, IFormFile? imagen)
        {
            if (ModelState.IsValid)
            {
                if (imagen != null && imagen.Length > 0)
                {
                    using (var stream = new MemoryStream())
                    {
                        imagen.CopyTo(stream);
                        enterprise.Image = stream.ToArray();
                    }
                }

                enterprise.UserId = int.Parse(HttpContext.Session.GetString("UserID"));
                _context.Enterprises.Add(enterprise);
                await _context.SaveChangesAsync();
                TempData["ShowModal"] = true;
            }
            else
            {
                var towns = await _context.TownShips
               .Where(t => t.Status == 1)
               .ToListAsync();
                ViewBag.TownShips = new SelectList(towns, "Id", "Name");

                if (imagen != null)
                {
                    using (var stream = new MemoryStream())
                    {
                        imagen.CopyTo(stream);
                        enterprise.Image = stream.ToArray();
                    }
                }
                

            }
            return View(enterprise);
        }





        [Authorize(Roles = "SuperUsuario")]
        public async Task<IActionResult> Edit(short id)
        {
            try
            {
                var enterprise = await _context.Enterprises.FindAsync(id);
                if (enterprise == null)
                {
                    return NotFound(); 
                }
                // Cargar la lista de ciudades disponibles
                var towns = await _context.TownShips
                    .Where(t => t.Status == 1)
                    .ToListAsync();
                // Construir la lista de selección
                ViewBag.TownShips = new SelectList(towns, "Id", "Name");
                if (enterprise.Image != null)
                {
                    TempData["CurrentImage"] = enterprise.Image;
                }

                return View(enterprise);
            }
            catch (Exception ex)
            { 
                return RedirectToAction("Error", "Home"); // Redirige a una página de error genérica
            }
        }


        [HttpPost]
        [Authorize(Roles = "SuperUsuario")]
        public async Task<IActionResult> Edit(Enterprise enterprise, IFormFile? imageIF)
        {
            try
            {
                // Cargar la lista de ciudades disponibles
                var towns = await _context.TownShips
                    .Where(t => t.Status == 1)
                    .ToListAsync();

                // Construir la lista de selección
                ViewBag.TownShips = new SelectList(towns, "Id", "Name");

                // Validación del formulario
                if (ModelState.IsValid)
                {
                    if (imageIF != null && imageIF.Length > 0)
                    {
                        using (var stream = new MemoryStream())
                        {
                            imageIF.CopyTo(stream);
                            enterprise.Image = stream.ToArray();
                        }
                    }
                    else if (TempData["CurrentImage"] is byte[] currentImage)
                    {
                        // Si no se ha cargado un nuevo archivo, restaura la imagen actual desde TempData
                        enterprise.Image = currentImage;
                    }

                    enterprise.LastUpdate = DateTime.Now;
                    _context.Enterprises.Update(enterprise);
                    await _context.SaveChangesAsync();
                    TempData["ShowModal"] = true;
                }
            }
            catch (Exception ex)
            {
                // Si ocurre un error, puedes manejarlo aquí y realizar un rollback de la transacción si es necesario
                ModelState.AddModelError(string.Empty, "Ocurrió un error al guardar los datos");
            }

            return View(enterprise);
        }





        [Authorize(Roles = "SuperUsuario")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var enterprise = await _context.Enterprises.FirstOrDefaultAsync(e => e.Id == id);
            if (enterprise == null)
            {
                return NotFound();
            }
            return PartialView("DeleteViewPartial",enterprise);
        }



        [Authorize(Roles = "SuperUsuario")]
        public async Task<IActionResult> ConfirmDelete(short? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var enterprise = await _context.Enterprises.FindAsync(id);
            if (enterprise == null)
            {
                return NotFound();
            }

            enterprise.Status = 0;        
            _context.Enterprises.Update(enterprise);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

    }
}

Views/Enterprise/Create.cshtml
@model Proyecto_Pymes.Models.DB.Enterprise;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<style>
    .imagen-redonda {
        border-radius: 50%; /* Hace que la imagen sea redonda */
        width: 200px; /* Ajusta el ancho de la imagen según tus preferencias */
        height: 200px; /* Ajusta la altura de la imagen según tus preferencias */
        object-fit: cover; /* Escala la imagen para que llene el contenedor sin deformarla */
        display: block; /* Convierte la imagen en un bloque para centrarla horizontalmente */
        margin: 0 auto; /* Margen automático izquierdo y derecho para centrar horizontalmente */
    }
</style>

<div class="container-fluid">

    <h1 style="text-align:center; color:rgb(255, 255, 255)">Registrar Asociacion</h1>


    <form method="post" action="/Enterprise/create" enctype="multipart/form-data" style="color: white">

        <div class="col-md-12">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="GroupName">Nombre de la Asociacion:</label>
                            <input type="text" class="form-control" asp-for="GroupName" id="" aria-describedby="helpId" placeholder="Ingrese el nombre de su Asociacion">
                            <span asp-validation-for="GroupName" class="text-danger" style="font-size: 12px;"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="IdTownShip">Municipio:</label>
                            <select class="form-control" asp-for="IdTownShip" asp-items="ViewBag.TownShips">
                                <option value="">Seleccione el Municipio</option>
                            </select>
                            <span asp-validation-for="IdTownShip" class="text-danger" style="font-size: 12px;"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="row">

                    <div class="col-md-6">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" >Descripción:</label>
                                <textarea class="form-control" asp-for="Description" id="" rows="5" placeholder="Ingrese una breve descripción" ></textarea>
                                <span asp-validation-for="Description" class="text-danger" style="font-size: 12px;"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Address" >Direccion:</label>
                                <textarea class="form-control" asp-for="Address" id="" rows="5" placeholder="Ingrese su Direccion" ></textarea>
                                <span asp-validation-for="Address" class="text-danger" style="font-size: 12px;"></span>
                            </div>
                        </div>
                    </div>


                    <div class="col-md-6">
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="form-group">
                                    <label asp-for="Image">Seleccione un Logo (opcional):</label>
                                    <div class="input-group">
                                        <input type="file" id="Image" name="imagen" class="form-control" asp-for="Image" placeholder="Cargar una imagen (opcional)" accept=".jpg, .jpeg, .png, .gif">
                                    </div>
                                    <span asp-validation-for="Image" class="text-danger" style="font-size: 12px;"></span>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12">
                          @*  <img id="previewImage" src="~/images/LoginImg/rompecabezas.png" class="imagen-redonda" />*@
                            @if (Model != null)
                            {
                                @if (Model.Image != null && Model.Image.Length > 0)
                                {
                                    <img id="previewImage" src="data:image/png;base64,@Convert.ToBase64String(Model.Image)" alt="Imagen actual" class="imagen-redonda" />
                                }                          
                            }else{
                                <img id="previewImage" src="~/images/LoginImg/rompecabezas.png" class="imagen-redonda" />
                            }         
                        </div>
                    </div>
  
                </div>
            </div>

            <div class="col-md-12 my-5 text-center">
                <div class="row">
                    <div class="col-md-3">
                    </div>                
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="text-center">
                                    <button type="submit" class="btn  btn-md  btn-block " style="background-color:#15718d; color:white;">Aceptar</button> <!-- Agregamos "btn-block" para que ocupe todo el ancho -->
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="text-center">
                                    <a asp-action="Index" class="btn  btn-md btn-block " style="background-color:#bb2727; color:white;">Cancelar</a> <!-- Agregamos "btn-block" para que ocupe todo el ancho -->
                                </div>
                            </div>
                        </div>                                                             
                    </div>
                    <div class="col-md-3">
                    </div>
                </div>
            </div>


        </div>
    </form>

    <div class="modal fade " id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-backdrop="static">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Mensaje</h5>
                </div>
                <div class="modal-body">
                    <p>Registro exitoso! <i class="fas fa-check-circle"></i></p>
                </div>
                <div class="modal-footer">
                    <a asp-controller="Enterprise" asp-action="Index" class="btn btn-warning">Aceptar</a>
                </div>
            </div>
        </div>
    </div>

    @*para poder manejar el Modal*@
    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }

        @if (TempData["ShowModal"] as bool? == true)
        {
            <script>
                $(document).ready(function () {
                    $('#exampleModalCenter').modal('show');
                });
            </script>
        }
    }


    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


    <script>
        // Función que se llama cuando se cambia el valor del campo de entrada de tipo file
        function showPreviewImage(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#previewImage').attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]);
            }
        }

        // Escucha el evento 'change' en el campo de entrada de tipo file
        $('#Image').on('change', function () {
            showPreviewImage(this);
        });   
    </script>

  

Views/Enterprise/DeleteViewPartial.cshtml
@model Proyecto_Pymes.Models.DB.Enterprise;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!-- Modal -->
<div class="modal fade" id="DeleteProduct-@Model.Id" aria-labelledby="DeleteProductLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 style="color:black" class="modal-title" id="exampleModalLabel">Confirmar Eliminación</h5>
            </div>
            <div style="color:black" class="modal-body">
                ¿Está seguro de que desea eliminar el siguiente registro? <br />
                <div>
                    <p> Asociaciones :  @Model.GroupName</p>
                </div>
            </div>
            <form action="/Enterprise/ConfirmDelete" method="post">
                <input hidden  asp-for="Id" />                          
                <div class="modal-footer">          
                    <a asp-action="Index" class="btn btn-secondary" data-dismiss="modal">Cancelar</a>
                    <button type="submit" class="btn btn-danger" >Eliminar</button>
                </div>
           </form>
        </div>
    </div>
</div>

Views/Enterprise/Edit.cshtml
@model Proyecto_Pymes.Models.DB.Enterprise;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
 
}

<style>
    .imagen-redonda {
        border-radius: 50%; /* Hace que la imagen sea redonda */
        width: 200px; /* Ajusta el ancho de la imagen según tus preferencias */
        height: 200px; /* Ajusta la altura de la imagen según tus preferencias */
        object-fit: cover; /* Escala la imagen para que llene el contenedor sin deformarla */
        display: block; /* Convierte la imagen en un bloque para centrarla horizontalmente */
        margin: 0 auto; /* Margen automático izquierdo y derecho para centrar horizontalmente */
    }
</style>


<div class="container-fluid">

    <h1 style="text-align:center; color:white;">Registrar Asociacion</h1>


    <form method="post" action="/Enterprise/Edit" enctype="multipart/form-data">

        <input hidden type="number" asp-for="Id" />
        <input hidden type="datetime" asp-for="RegisterDate"/>
        <input hidden type="number" asp-for="Status" />
        <input hidden type="number" asp-for="UserId" />
       

        <div class="col-md-12">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="GroupName" style="color: white;">Nombre de la Asociacion :</label>
                            <input type="text" class="form-control" asp-for="GroupName" id="" aria-describedby="helpId" placeholder="Ingrese el nombre de su Asociacion" style="color: black;">
                            <span asp-validation-for="GroupName" class="text-danger" style="font-size: 12px;"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="IdTownShip" style="color: white;">Ciudad:</label>
                            <select class="form-control" asp-for="IdTownShip"  style="color: black;">
                                @foreach (var item in ViewBag.TownShips)
                                {
                                    <option value="@item.Value" selected="@(item.Value == Model.IdTownShip.ToString())" >@item.Text</option>
                                }
                            </select>
                            <span asp-validation-for="IdTownShip" class="text-danger" style="font-size: 12px;"></span>
                        </div>
                    </div>

                </div>
            </div>
            <div class="col-md-12">
                <div class="row">

                    <div class="col-md-6">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" style="color:white;">Descripción:</label>
                                <textarea class="form-control" asp-for="Description" id="" rows="5" placeholder="Ingrese una breve descripción" style="color: black;"></textarea>
                                <span asp-validation-for="Description" class="text-danger" style="font-size: 12px;"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Address" style="color:white;">Direccion:</label>
                                <textarea class="form-control" asp-for="Address" id="" rows="5" placeholder="Ingrese su Direccion" style="color: black;"></textarea>
                                <span asp-validation-for="Address" class="text-danger" style="font-size: 12px;"></span>
                            </div>
                        </div>
                    </div>


                    <div class="col-md-6">
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="form-group">
                                    <label asp-for="Image" style="color: white;">Seleccione una Logo (opcional):</label>
                                    <div class="input-group">
                                        <input type="file" id="imageIF" name="imageIF" class="form-control" style="color: black;" placeholder="Cargar una imagen (opcional)" accept=".jpg, .jpeg, .png, .gif">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <label asp-for="Image" style="color: white;">Imagen Actual:</label>
                            @if (Model.Image != null && Model.Image.Length > 0)
                            {
                                <img id="previewImage" src="data:image/png;base64,@Convert.ToBase64String(Model.Image)" alt="Imagen actual" class="imagen-redonda" />
                            }
                            else
                            {
                                <img id="previewImage" src="~/images/LoginImg/rompecabezas.png" class="imagen-redonda" />
                            }
                        </div>
                    </div>

                </div>
            </div>

            <div class="col-md-12 my-5 text-center">
                <div class="row">

                    <div class="col-md-3">
                    </div>

                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="text-center">
                                    <button type="submit" class="btn btn-md  btn-block " style="background-color:#15718d; color:white;">Editar</button> <!-- Agregamos "btn-block" para que ocupe todo el ancho -->
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="text-center">
                                    <a asp-action="Index" class="btn btn-md btn-block " style="background-color:#bb2727; color:white;">Cancelar</a> <!-- Agregamos "btn-block" para que ocupe todo el ancho -->
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3">
                    </div>
                </div>
            </div>


        </div>
    </form>
</div>


<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Mensaje</h5>
            </div>
            <div class="modal-body">
                <p>¡La actualización se ha completado con éxito!<i class="fas fa-check-circle"></i></p>
            </div>
            <div class="modal-footer">
                <a asp-controller="Enterprise" asp-action="Index" class="btn btn-warning">Aceptar</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    @if (TempData["ShowModal"] as bool? == true)
    {
        <script>
            $(document).ready(function () {
                $('#exampleModalCenter').modal('show');
            });
        </script>
    }
}



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    // Función que se llama cuando se cambia el valor del campo de entrada de tipo file
    function showPreviewImage(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#previewImage').attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    // Escucha el evento 'change' en el campo de entrada de tipo file
    $('#Image').on('change', function () {
        showPreviewImage(this);
    });
</script>


@*para poder cargar la imagen de Entrada en el imput*@
<script>
    // Verifica si el modelo ya tiene una imagen
    var currentImage = '@Model.Image';

    if (currentImage) {
        // Si existe una imagen, establece el valor del campo de entrada de archivo
        document.getElementById('Image').value = currentImage;
    }
</script>