Proyecto_Pymes/Models/DB/BusinessManager.cs
using System;
using System.Collections.Generic;

namespace Proyecto_Pymes.Models.DB;

public partial class BusinessManager
{
    public int Id { get; set; }

    public string? CorporateNumber { get; set; }

    public byte Status { get; set; }

    public DateTime RegisterDate { get; set; }

    public DateTime? LastUpdate { get; set; }

    public short IdEnterprise { get; set; }

    public int UserId { get; set; }

    public virtual Enterprise? IdEnterpriseNavigation { get; set; } = null!;

    public virtual Person? IdNavigation { get; set; } = null!;
}

Proyecto_Pymes/Controllers/BusinessManagersController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Proyecto_Pymes.Models.DB;

namespace Proyecto_Pymes.Controllers
{
    public class BusinessManagersController : Controller
    {
        private readonly DbPymesContext _context;

        public BusinessManagersController(DbPymesContext context)
        {
            _context = context;
        }

        // GET: BusinessManagers1
        public async Task<IActionResult> Index()
        {
            var dbPymesContext = _context.BusinessManagers.Include(b => b.IdEnterpriseNavigation).Include(b => b.IdNavigation).Where(b => b.Status == 1);
            return View(await dbPymesContext.ToListAsync());
        }

        // GET: BusinessManagers1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BusinessManagers == null)
            {
                return NotFound();
            }

            var businessManager = await _context.BusinessManagers
                .Include(b => b.IdEnterpriseNavigation)
                .Include(b => b.IdNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (businessManager == null)
            {
                return NotFound();
            }

            return View(businessManager);
        }

        // GET: BusinessManagers1/Create
        public IActionResult Create()
        {
            ViewData["IdEnterprise"] = new SelectList(_context.Enterprises, "Id", "GroupName");
            return View();
        }

        // POST: BusinessManagers1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BusinessManager bs)
        {
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    if (ModelState.IsValid)
                    {



                        //registro para la persona-------------------------------------------------------------------------------------
                        _context.People.Add(bs.IdNavigation);
                        await _context.SaveChangesAsync();

                        string userID = HttpContext.Session.GetString("UserID");
                        bs.RegisterDate = DateTime.ParseExact(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff"), "yyyy-MM-dd HH:mm:ss.fff", CultureInfo.InvariantCulture);
                        bs.UserId = int.Parse(userID);
                        _context.BusinessManagers.Add(bs);
                        await _context.SaveChangesAsync();

                        //registro para el Usuario----------------------------------------------------------------------------
                        User user = Credentials(bs.IdNavigation);
                        _context.Users.Add(user);
                        await _context.SaveChangesAsync();

                        // Commit la transacción si todo fue exitoso
                        transaction.Commit();
                        //PARA EL MODAL
                        TempData["ShowModal"] = true;
                    }
                }
                catch (Exception)
                {
                    // Si se produce una excepción, puedes realizar un rollback de la transacción
                    transaction.Rollback();
                    ModelState.AddModelError(string.Empty, "Ha ocurrido un error en la transacción.");
                }
            }
            return View();
        }

        public async Task<IActionResult> Edit(int? id)
        {
           
            var businessManager = await _context.BusinessManagers.FindAsync(id);
            var people = await _context.People.FindAsync(id);

            if (businessManager == null || people == null || id == null)
            {
                return NotFound();
            }
            ViewData["IdEnterprise"] = new SelectList(_context.Enterprises, "Id", "GroupName", businessManager.IdEnterprise);
            return View(businessManager);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(BusinessManager bs)
        {
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        Person per = bs.IdNavigation;
                        string sql = @"UPDATE Person
                                    SET name = @Name, lastName = @LastName, secondLastName = @SecondLastName, email = @Email, phoneNumber = @PhoneNumber, gender = @Gender, ci = @CI ,lastUpdate = CURRENT_TIMESTAMP
                                    WHERE id = @PersonId; ";

                        // Crea objetos SqlParameter para los parámetros de la consulta
                        SqlParameter[] parameters = new SqlParameter[]
                        {
                            new SqlParameter("@Name", per.Name),
                            new SqlParameter("@LastName", per.LastName),
                            new SqlParameter("@SecondLastName", per.SecondLastName),
                            new SqlParameter("@Email", per.Email),
                            new SqlParameter("@PhoneNumber", per.PhoneNumber),
                            new SqlParameter("@Gender", per.Gender),
                            new SqlParameter("@CI", per.Ci),
                            new SqlParameter("@PersonId", bs.Id)//OJO
                        };
                        int affectedRows = await _context.Database.ExecuteSqlRawAsync(sql, parameters);


                        //para la tabla Productor
                        string sql1 = @"UPDATE BusinessManager
                                    SET corporateNumber = @corporateNumber, lastUpdate = CURRENT_TIMESTAMP
                                    WHERE id = @BusinessManagerId;";
                        // Crea objetos SqlParameter para los parámetros de la consulta
                        SqlParameter[] parameters1 = new SqlParameter[]
                        {
                            new SqlParameter("@corporateNumber", bs.CorporateNumber),
                            new SqlParameter("@BusinessManagerId", bs.Id)
                        };
                        int affectedRows1 = await _context.Database.ExecuteSqlRawAsync(sql1, parameters1);

                        if (affectedRows > 0 && affectedRows1 > 0)
                        {
                            // Si todo ha ido bien, realiza el commit de la transacción
                            transaction.Commit();
                            TempData["ShowModal"] = true;
                        }

                        return RedirectToAction("Edit", new { id = bs.Id }); // Redirecciona a la página de lista después de la edición
                    }
                    else
                    {
                        // Si hay errores en el modelo, no se realizará el commit de la transacción
                        return View(bs);
                    }
                }
                catch (Exception ex)
                {
                    // Si ocurre un error, puedes manejarlo aquí y realizar un rollback de la transacción si es necesario
                    transaction.Rollback();
                    ModelState.AddModelError(string.Empty, "Ocurrió un error al guardar los datos.");
                    return View(bs);
                }
            }
        }


        // GET: BusinessManagers1/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null || _context.BusinessManagers == null)
        //    {
        //        return NotFound();
        //    }

        //    var businessManager = await _context.BusinessManagers.FindAsync(id);
        //    if (businessManager == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["IdEnterprise"] = new SelectList(_context.Enterprises, "Id", "Id", businessManager.IdEnterprise);
        //    ViewData["Id"] = new SelectList(_context.People, "Id", "Id", businessManager.Id);
        //    return View(businessManager);
        //}

        // POST: BusinessManagers1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // GET: BusinessManagers1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var person = await _context.People.FirstOrDefaultAsync(m => m.Id == id);
            if (person == null)
            {
                return NotFound();
            }
            TempData["BsToDelete"] = person.Id;
            TempData["Name"] = person.Name;
            TempData["lastName"] = person.LastName;
            TempData["SeconlastName"] = person.SecondLastName;
            TempData["ShowModalDelete"] = true;

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult UpdateShowModalDelete(bool value)
        {
            TempData["ShowModalDelete"] = value;
            return Json(new { success = true });
        }


        public async Task<IActionResult> ConfirmDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var bs = await _context.BusinessManagers.FindAsync(id);
            if (bs == null)
            {
                return NotFound();
            }

Proyecto_Pymes/Views/BusinessManagers/Create.cshtml
@model Proyecto_Pymes.Models.DB.BusinessManager

@{
    ViewData["Title"] = "Create";
}

<h1 style="color:white; text-align:center;">Registrar Adminastror</h1>

<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdNavigation.Name" class="control-label" style="color:white;">Nombre</label>
                <input asp-for="IdNavigation.Name" class="form-control" />
                <span asp-validation-for="IdNavigation.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNavigation.LastName" class="control-label" style="color:white;">Primer Apellido</label>
                <input asp-for="IdNavigation.LastName" class="form-control" />
                <span asp-validation-for="IdNavigation.LastName" class="text-danger"></span>
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="IdNavigation.SecondLastName" class="control-label" style="color:white;">Segundo Apellido</label>
                <input asp-for="IdNavigation.SecondLastName" class="form-control" />
                <span asp-validation-for="IdNavigation.SecondLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNavigation.Email" class="control-label" style="color:white;">Email</label>
                <input asp-for="IdNavigation.Email" class="form-control" />
                <span asp-validation-for="IdNavigation.Email" class="text-danger"></span>
            </div>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="IdNavigation.PhoneNumber" class="control-label" style="color:white;">Celular</label>
                <input asp-for="IdNavigation.PhoneNumber" class="form-control" />
                <span asp-validation-for="IdNavigation.PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNavigation.Gender" class="control-label" style="color:white;">Genero</label>
                <input asp-for="IdNavigation.Gender" class="form-control" />
                <span asp-validation-for="IdNavigation.Gender" class="text-danger"></span>
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="IdNavigation.Ci" class="control-label" style="color:white;">CI</label>
                <input asp-for="IdNavigation.Ci" class="form-control" />
                <span asp-validation-for="IdNavigation.Ci" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CorporateNumber" class="control-label" style="color:white;">Numero Corporativo</label>
                <input asp-for="CorporateNumber" class="form-control" />
                <span asp-validation-for="CorporateNumber" class="text-danger"></span>
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label asp-for="IdEnterprise" class="control-label" style="color:white;">Asociacion</label>
            <select asp-for="IdEnterprise" class="form-control" asp-items="ViewBag.IdEnterprise"></select>
        </div>
    </div>
    <div class="form-group text-center">
        <button type="submit" value="Create" class="btn btn-warning ">Aceptar</button>
    </div>

  
   

</div>


<div>
    <a asp-action="Index" class="text-warning">Volver a la lista </a>
</div>

<div class="modal fade " id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Mensaje</h5>
            </div>
            <div class="modal-body">
                <p>Registro exitoso! <i class="fas fa-check-circle"></i></p>
            </div>
            <div class="modal-footer">
                <a asp-controller="BusinessManagers" asp-action="Index" class="btn btn-warning">Aceptar</a>
            </div>
        </div>
    </div>
</div>





@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    @if (TempData["ShowModal"] as bool? == true)
    {
        <script>
            $(document).ready(function () {
                $('#exampleModalCenter').modal('show');
            });
        </script>
    }
}

Proyecto_Pymes/Views/BusinessManagers/Delete.cshtml
@model Proyecto_Pymes.Models.DB.BusinessManager

@{
    ViewData["Title"] = "Delete";
}

<h1 style="color:white; text-align:center;">Eliminar</h1>

<h3 style="color:white;">Esta seguro que quiere eliminar esto?</h3>
<div>
    <h4>BusinessManager</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CorporateNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CorporateNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastUpdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastUpdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEnterpriseNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEnterpriseNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdNavigation.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Proyecto_Pymes/Views/BusinessManagers/Details.cshtml
@model Proyecto_Pymes.Models.DB.BusinessManager

@{
    ViewData["Title"] = "Details";
}

<h1 style="color:white; text-align:center;">Detalles</h1>

<div>
    <h4 style="color:white;">Administrador de Empresa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CorporateNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CorporateNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastUpdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastUpdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEnterpriseNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEnterpriseNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdNavigation.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Proyecto_Pymes/Views/BusinessManagers/Edit.cshtml
@model Proyecto_Pymes.Models.DB.BusinessManager

@{
    ViewData["Title"] = "Edit";
}

<h1 >Editar</h1>

<h4>Administrador </h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdNavigation.Name" class="control-label" style="color:white;">Nombre</label>
                <input asp-for="IdNavigation.Name" class="form-control" />
                <span asp-validation-for="IdNavigation.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNavigation.LastName" class="control-label" style="color:white;">Primer Apellido</label>
                <input asp-for="IdNavigation.LastName" class="form-control" />
                <span asp-validation-for="IdNavigation.LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNavigation.SecondLastName" class="control-label" style="color:white;">Segundo Apellido</label>
                <input asp-for="IdNavigation.SecondLastName" class="form-control" />
                <span asp-validation-for="IdNavigation.SecondLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNavigation.Email" class="control-label" style="color:white;"></label>
                <input asp-for="IdNavigation.Email" class="form-control" />
                <span asp-validation-for="IdNavigation.Email" class="text-danger">Email</span>
            </div>
            <div class="form-group">
                <label asp-for="IdNavigation.PhoneNumber" class="control-label" style="color:white;">Celular</label>
                <input asp-for="IdNavigation.PhoneNumber" class="form-control" />
                <span asp-validation-for="IdNavigation.PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNavigation.Gender" class="control-label" style="color:white;">Genero</label>
                <input asp-for="IdNavigation.Gender" class="form-control" />
                <span asp-validation-for="IdNavigation.Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdNavigation.Ci" class="control-label" style="color:white;"></label>
                <input asp-for="IdNavigation.Ci" class="form-control" />
                <span asp-validation-for="IdNavigation.Ci" class="text-danger">CI</span>
            </div>
            <div class="form-group">
                <label asp-for="CorporateNumber" class="control-label" style="color:white;">Numero Corporativo</label>
                <input asp-for="CorporateNumber" class="form-control" />
                <span asp-validation-for="CorporateNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEnterprise" class="control-label" style="color:white;">Asociacion </label>
                <select asp-for="IdEnterprise" class="form-control" asp-items="ViewBag.IdEnterprise"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Mensaje</h5>
            </div>
            <div class="modal-body">
                <p>Administrador de Empresa actualizado correctamente! <i class="fas fa-check-circle"></i></p>
            </div>
            <div class="modal-footer">
                <a asp-controller="BusinessManagers" asp-action="Index" class="btn btn-warning">Aceptar</a>
            </div>
        </div>
    </div>
</div>


</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    @if (TempData["ShowModal"] as bool? == true)
    {
        <script>
            $(document).ready(function () {
                $('#exampleModalCenter').modal('show');
            });
        </script>
    }
}

Proyecto_Pymes/Views/BusinessManagers/Index.cshtml
@model IEnumerable<Proyecto_Pymes.Models.DB.BusinessManager>

@{
    ViewData["Title"] = "Index";
}

<h1 style="color:white;">Administracion </h1>

<p>
    <a asp-action="Create" class="btn btn-warning float-right">Nuevo Registro </a>
<table class="table" style="color:white;">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdNavigation.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdNavigation.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdNavigation.SecondLastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdNavigation.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdNavigation.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdNavigation.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdNavigation.Ci)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdEnterpriseNavigation.GroupName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CorporateNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdNavigation.Name)
                <td>
                        @Html.DisplayFor(modelItem => item.IdNavigation.LastName)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.IdNavigation.SecondLastName)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.IdNavigation.Email)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.IdNavigation.PhoneNumber)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.IdNavigation.Gender)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.IdNavigation.Ci)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.IdEnterpriseNavigation.GroupName)
                </td>
                <td>
                        @Html.DisplayFor(modelItem => item.CorporateNumber)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> ||
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-secondary">
                        <i class="fas fa-trash"></i> Delete
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmar Eliminación</h5>
            </div>
            <div class="modal-body">
                ¿Está seguro de que desea eliminar el siguiente registro? <br />
                Nombre: @TempData["Name"] @TempData["lastName"] @TempData["SeconlastName"]
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <a asp-action="ConfirmDelete" asp-route-id="@TempData["BsToDelete"]" class="btn btn-danger">Eliminar</a>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @if (TempData["ShowModalDelete"] as bool? == true)
    {
        <script>
            $(document).ready(function () {
                $('#exampleModal').modal('show');


                $('#exampleModal').on('hidden.bs.modal', function () {

                    $.ajax({
                        url: '/BusinessManagers/UpdateShowModalDelete',
                        method: 'POST',
                        data: { value: false }, // Enviar el valor false al servidor
                        success: function (data) {
                            // Opcional: Puedes realizar acciones adicionales después de cambiar el valor
                        }
                    });
                });
            });
        </script>
    }
}