Proyecto_Pymes/Controllers/ProducerController.cs
using Microsoft.AspNetCore.Mvc;
using Proyecto_Pymes.Models.DB;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Collections.Generic;
using System;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Data.SqlClient;
using System.Reflection;

namespace Proyecto_Pymes.Controllers
{
    public class ProducerController : Controller
    {

        private readonly DbPymesContext _context;

        public ProducerController(DbPymesContext context)
        {
            _context = context;
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}
        //para poder recuperar los datos
        public async Task<IActionResult> Index()
        {
            var sql = @"SELECT *
                        FROM Person
                        WHERE id IN (
                            SELECT pr.id
                            FROM Enterprise e
                            INNER JOIN producerCompany pc ON e.id = pc.idEnterprise
                            INNER JOIN Producer pr ON pr.id = pc.idProducer
                            WHERE pr.status = 1 AND e.id = @EnterpriseId )";
            //recuperamos el id de la empresa don de se filtrar los productores
            string enterpriseId = HttpContext.Session.GetString("EnterpriseID");
            var people = await _context.People.FromSqlRaw(sql, new SqlParameter("@EnterpriseId", enterpriseId) ).ToListAsync();

            return View(people);
        }


        /// <summary>
        /// para el Insert de Productor------------------------------------------------------------------------------------------------------------
        /// </summary>
        /// <returns></returns>
        // GET: People/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Producer producer)
        {
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        //registro para la persona-------------------------------------------------------------------------------------
                        _context.People.Add(producer.IdNavigation);
                        await _context.SaveChangesAsync();

                        //registro para el Productor---------------------------------------------------------------------------------
                        int personId = producer.IdNavigation.Id;
                        producer.Id = personId;//OJO------------------------------------
                        string userID = HttpContext.Session.GetString("UserID");
                        producer.UserId = int.Parse(userID);
                        _context.Producers.Add(producer);
                        await _context.SaveChangesAsync();

                        //registro para el Usuario----------------------------------------------------------------------------
                        User user = Credentials(producer.IdNavigation);
                        _context.Users.Add(user);
                        await _context.SaveChangesAsync();

                        //registro para la tabla de muchos a muchos---------------------------------------------------------------------
                        ProducerCompany company= new ProducerCompany();
                        string enterpriseId = HttpContext.Session.GetString("EnterpriseID");
                        company.IdProducer = personId;
                        company.IdEnterprise = short.Parse(enterpriseId);//OJO----------------------------------
                        company.StartDate = DateTime.Now;
                        _context.ProducerCompanies.Add(company);
                        await _context.SaveChangesAsync();

                        // Commit la transacción si todo fue exitoso
                        transaction.Commit();
                        //PARA EL MODAL
                        TempData["ShowModal"] = true;
                    }
                }
                catch (Exception)
                {
                    // Si se produce una excepción, puedes realizar un rollback de la transacción
                    transaction.Rollback();
                    ModelState.AddModelError(string.Empty, "Ha ocurrido un error en la transacción.");
                }
            }
            return View();
        }

        private User Credentials(Person person)
        {
            User user = new User();
            string userName = (person.Name[0].ToString() + person.LastName[0].ToString() + person.SecondLastName[0].ToString()).ToUpper() + RandomNumber();
            user.Id = person.Id;
            user.UserName = userName;
            user.Password = PasswordGeneration(person);
            user.Role = "Productor";
            user.UserId = 1;//OJO
            return user;
        }

        private string RandomNumber()
        {
            string num = "";
            Random random = new Random();
            for(int i = 0; i<7 ; i++)
            {
                int numeroAleatorio = random.Next(0, 9);
                num += numeroAleatorio;
            }
            return num;
        }
        private byte[] PasswordGeneration(Person person)
        {
            using (MD5 md5 = MD5.Create())
            {
                string password = person.Ci.Substring(0, 5) + person.Email.Substring(0,2);
                byte[] inputBytes = Encoding.ASCII.GetBytes(password);
                byte[] hashBytes = md5.ComputeHash(inputBytes);
                return hashBytes;
            }
        }


        //para poder Editar al Productor
        // GET: People/Create
        // GET: People/Delete/5

        // GET: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {        
            var prod = await _context.Producers.FindAsync(id);
            var people = await _context.People.FindAsync(id);
            
            if (prod == null || people == null || id == null)
            {
                return NotFound();
            }

            return View(prod);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Producer producer)
        {
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        Person per = producer.IdNavigation;
                        string sql = @"UPDATE Person
                                    SET name = @Name, lastName = @LastName, secondLastName = @SecondLastName, email = @Email, phoneNumber = @PhoneNumber, gender = @Gender, ci = @CI ,lastUpdate = CURRENT_TIMESTAMP
                                    WHERE id = @PersonId; ";

                        // Crea objetos SqlParameter para los parámetros de la consulta
                        SqlParameter[] parameters = new SqlParameter[]
                        {
                            new SqlParameter("@Name", per.Name),
                            new SqlParameter("@LastName", per.LastName),
                            new SqlParameter("@SecondLastName", per.SecondLastName),
                            new SqlParameter("@Email", per.Email),
                            new SqlParameter("@PhoneNumber", per.PhoneNumber),
                            new SqlParameter("@Gender", per.Gender),
                            new SqlParameter("@CI", per.Ci),
                            new SqlParameter("@PersonId", producer.Id)//OJO
                        };
                        int affectedRows = await _context.Database.ExecuteSqlRawAsync(sql, parameters);


                        //para la tabla Productor
                        string sql1 = @"UPDATE Producer
                                    SET longitude = @Longitude, latitude = @Latitude, lastUpdate = CURRENT_TIMESTAMP
                                    WHERE id = @ProducerId;";
                        // Crea objetos SqlParameter para los parámetros de la consulta
                        SqlParameter[] parameters1 = new SqlParameter[]
                        {
                            new SqlParameter("@Longitude", producer.Longitude),
                            new SqlParameter("@Latitude", producer.Latitude),
                            new SqlParameter("@ProducerId", producer.Id)
                        };
                        int affectedRows1 = await _context.Database.ExecuteSqlRawAsync(sql1, parameters1);

                        if (affectedRows > 0 && affectedRows1 > 0)
                        {
                            // Si todo ha ido bien, realiza el commit de la transacción
                            transaction.Commit();
                            TempData["ShowModal"] = true;
                        }

                        return RedirectToAction("Edit", new { id = producer.Id }); // Redirecciona a la página de lista después de la edición
                    }
                    else
                    {
                        // Si hay errores en el modelo, no se realizará el commit de la transacción
                        return View(producer);
                    }
                }
                catch (Exception ex)
                {
                    // Si ocurre un error, puedes manejarlo aquí y realizar un rollback de la transacción si es necesario
                    transaction.Rollback();
                    ModelState.AddModelError(string.Empty, "Ocurrió un error al guardar los datos.");
                    return View(producer);
                }
            }
        }



        // GET: People/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var person = await _context.People.FirstOrDefaultAsync(m => m.Id == id);

Proyecto_Pymes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.1.0/css/adminlte.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light" id="navPrincipal">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button" style="color: white;"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item" id="idSettings">
                    <a class="nav-link" href="#">⚙</a>
                </li>
            </ul>
        </nav>
        <!-- Sidebar -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4 lateralBar">
            @* <a href="#" class="brand-link">
            <span class="brand-text font-weight-light">UNDERGAME</span>
            </a> *@
            <div class="user-panel d-flex" id="sec1">
                <div class="image imgUser">
                    <a asp-action="Index"><img src="~/images/loginimg/rompecabezas.png" /></a>
                </div>

                <div class="info" style="margin-left: 18px; padding:auto">
                    <p id="enterprise-name">ENTERPRISE</p>
                </div>

            </div>

            <nav class="mt-2">
                <div class="user-panel d-flex" id="sec1">
                    <div class="image imgUser">
                        <a href=""><img src="~/images/loginimg/hombre.png" class="img-circle elevation-2" alt="User Image" /></a>
                    </div>

                    <div class="info" style="margin-left: 18px; padding:auto">
                        <p id="user-name">Andrew Tale</p>
                    </div>

                </div>
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false" style="margin-top: 30px; margin-left: 8px;">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                    <li class="nav-item menu-open">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-gamepad"></i>
                            <p>
                                Overview
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a asp-action="ProductCRUD" class="nav-link">
                                    <i class="fa-plane fas nav-icon"></i>
                                    <p>Product</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a asp-controller="Producer" asp-action="Index" class="nav-link">
                                    <i class="fas fa-list-alt nav-icon"></i>
                                    <p>Productor</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="BusinessManagers" class="nav-link">
                                    <i class="fas fa-list-alt nav-icon"></i>
                                    <p>Admin. Empresa</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="../../index3.html" class="nav-link">
                                    <i class="fas fa-shopping-bag nav-icon"></i>
                                    <p>Products</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="TownShips" class="nav-link">
                                    <i class="fas fa-users nav-icon"></i>
                                    <p>Municipios</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-header"><hr></li>
                    <li class="nav-item">
                        <a asp-action="Users" class="nav-link">
                            <i class="nav-icon fas fa-address-card "></i>
                            <p>
                                User
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="../gallery.html" class="nav-link">
                            <i class="nav-icon fas fa-cog"></i>
                            <p>
                                Settings
                            </p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="../../iframe.html" class="nav-link">
                            <p style="opacity:.8">Help</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://adminlte.io/docs/3.1/" class="nav-link">
                            <p style="opacity:.8">Contact us</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a asp-action="Session" class="nav-link">
                            <p style="opacity:.8">Log out</p>
                        </a>
                    </li>

                </ul>
            </nav>

            <!-- /.sidebar-menu -->
        </aside>
        <!-- Content Wrapper -->
        <div class="content-wrapper back">
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
        </div>
        <!-- Footer -->
        <footer class="main-footer">
            <div class="float-right d-none d-sm-inline">
                Version 1.0
            </div>
            &copy; 2023 - WebApplication1
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
   @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>  OJO*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.1.0/js/adminlte.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>